# Generated by Django 6.0 on 2025-12-07 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wprowadź czytelną nazwę ćwiczenia.', max_length=100, unique=True, verbose_name='Nazwa ćwiczenia')),
                ('description', models.TextField(blank=True, help_text='Krótki opis ćwiczenia (opcjonalnie).', verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Data i czas rozpoczęcia')),
                ('end', models.DateTimeField(verbose_name='Data i czas zakończenia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.DecimalField(decimal_places=2, help_text='Podaj obciążenie w kilogramach.', max_digits=6, verbose_name='Obciążenie (kg)')),
                ('sets', models.PositiveIntegerField(help_text='Ile serii wykonano.', verbose_name='Liczba serii')),
                ('reps', models.PositiveIntegerField(help_text='Ile powtórzeń w jednej serii.', verbose_name='Powtórzenia w serii')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed', to='workout.exercisetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_exercises', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_exercises', to='workout.trainingsession')),
            ],
        ),
    ]
